# release.yml
name: Release
on:
  pull_request:
    types: [closed]
    branches:
      - master
      - main

jobs:
  release:
    # Only run if the PR is merged (not just closed)
    if: github.event.pull_request.merged == true
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fetch PR commits
        run: git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
